apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorty
  labels:
    app: shorty
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '2112'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorty
  template:
    metadata:
      labels:
        app: shorty
    spec:
      containers:
      - name: shorty
        image: ghcr.io/nwehr/shorty/server:1dd90f05
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: default
      imagePullSecrets:
      - name: ghcr-credentials