---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shorty
  name: shorty
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: shorty
  type: ClusterIP
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: prometheus
# spec:
#   endpoints:
#   - interval: 10s
#     targetPort: '2112'
#     path: /metrics
#   namespaceSelector:
#     matchNames:
#     - shorty
#   selector:
#     matchLabels:
#       app: shorty
