apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorty
  labels:
    app: shorty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shorty
  template:
    metadata:
      labels:
        app: shorty
    spec:
      containers:
      - name: shorty
        image: nwehr/shorty-server:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: oauth-config