# needs to be version 2 for mem_limit
version: "2"

services:
  postgres:
    image: postgres:12
    mem_limit: 256m
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    image: ghcr.io/nwehr/shorty/server
    build:
      context: ../
      dockerfile: server.Dockerfile
    mem_limit: 64m
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URLS: ${REDIS_URLS}
      PUBLIC_URL: ${PUBLIC_URL}
      AUTHORIZATION_URL: ${AUTHORIZATION_URL}
      TOKEN_URL: ${TOKEN_URL}
      LOGOUT_URL: ${LOGOUT_URL}
      REDIRECT_URL: ${REDIRECT_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    depends_on:
      - postgres
    ports: 
     - "8080:8080"
  
volumes:
  pg_data: